-- Fresh database only. Select/create an EMPTY database before running.
-- No tables or records are dropped by this script.

CREATE TABLE IF NOT EXISTS users (
    User_ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    contact_no VARCHAR(20) DEFAULT NULL,
    location VARCHAR(150) DEFAULT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vehicle_brand (
    Brand_ID INT AUTO_INCREMENT PRIMARY KEY,
    Brand_Name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS vehicle_model (
    Model_ID INT AUTO_INCREMENT PRIMARY KEY,
    Brand_ID INT NOT NULL,
    Model_Name VARCHAR(50) NOT NULL,
    FOREIGN KEY (Brand_ID) REFERENCES vehicle_brand(Brand_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS vehicle (
    Vehicle_ID INT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Model_ID INT NOT NULL,
    brand VARCHAR(50) NOT NULL,
    fuel_type VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(30) NOT NULL,
    Year INT DEFAULT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES users(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Model_ID) REFERENCES vehicle_model(Model_ID)
);

CREATE TABLE IF NOT EXISTS chat_history (
    chat_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    vehicle_id INT NOT NULL,
    session_id VARCHAR(64) NULL,
    metadata_json TEXT NULL,
    sender VARCHAR(20) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(User_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS symptom (
    Symptom_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Vehicle_ID INT DEFAULT NULL,
    description TEXT NOT NULL,
    reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Vehicle_ID) REFERENCES vehicle(Vehicle_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS diagnosis (
    Diagnosis_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Symptom_ID BIGINT NOT NULL,
    response_type ENUM('GREETING', 'CLARIFICATION', 'DIAGNOSIS') DEFAULT NULL,
    session_id VARCHAR(64) NULL,
    Fault_Name VARCHAR(100) DEFAULT NULL,
    Possible_Cause TEXT DEFAULT NULL,
    confidence_level DOUBLE DEFAULT NULL,
    Safe_To_Drive BOOLEAN DEFAULT NULL,
    min_cost DOUBLE DEFAULT NULL,
    max_cost DOUBLE DEFAULT NULL,
    cost_estimate_source VARCHAR(50) NULL,
    cost_currency VARCHAR(10) NULL,
    cost_assumptions VARCHAR(255) NULL,
    model_used VARCHAR(50) DEFAULT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Symptom_ID) REFERENCES symptom(Symptom_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS garage (
    Garage_ID INT AUTO_INCREMENT PRIMARY KEY,
    Garage_Name VARCHAR(100) NOT NULL,
    Location VARCHAR(150) NOT NULL,
    Specialization VARCHAR(100) DEFAULT NULL,
    Rating DOUBLE DEFAULT NULL,
    Phone_No VARCHAR(30) DEFAULT NULL,
    latitude DOUBLE DEFAULT NULL,
    longitude DOUBLE DEFAULT NULL,
    is_demo BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS garage_recommendation (
    Recommendation_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    User_ID INT NOT NULL,
    Garage_ID INT NOT NULL,
    Diagnosis_ID BIGINT DEFAULT NULL,
    Distance DOUBLE DEFAULT NULL,
    Match_Score DOUBLE DEFAULT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (User_ID) REFERENCES users(User_ID) ON DELETE CASCADE,
    FOREIGN KEY (Garage_ID) REFERENCES garage(Garage_ID) ON DELETE CASCADE
);
